### ISSUE TITLE
Check code example formatting

### ISSUE THREAD

**Issue by korenmiklos** [korenmiklos/stata-debate#1]
@martonfleck please check the two slides at the end of https://github.com/korenmiklos/stata-debate/blob/main/slides.pdf

We can change the formatting a little, but not much.

1. Should we keep comments? Latex syntax highlighting only knows `/* */` style comments, which look pretty but are a bit too much. We can also play to the advantage of Stata that its code is highly readable.
2. Isn't regression table too small?
3. Relatedly, shall we stick to the 2-column format? I kind of like it, especially for the graph (which I may make a bit smaller). I can also make them reveal only after the code.

**Comment by martonfleck** [comment]
@korenmiklos 
1. I think we should keep comments; I see two options
a) keep as is
b) insert code as snapshot from the do file editor. 

Let me know if you prefer b) and I can upload the snapshots.

2. Regression table size is fine with me, the point is the overall look of it, not the specific coefficients or anything like that.

3. The 2-column format looks good. I suppose the first part of the presentation if work in progress, but slide 2 is currently missing a proper title.
